### ISSUE TITLE
Disable Redirect to HTTPS

### ISSUE THREAD

**Issue by charredchar** [kylejramstad/garage-pi-v2#8]
I have been attempting to put this behind an Apache Reverse Proxy but with it automatically redirecting to HTTPS it has been causing issues. I have Apache running Certbot and already automatically forcing HTTPS so I don't really need it inside my own network.

I don't mind modifying something myself if need be to disable HTTPS or the redirect but it would also be nice if it was in the settings to turn it off. This way we could also keep HTTPS enabled just in case but not force the redirect.

**Comment by kylejramstad** [comment]
Sorry for the late reply. My notifications seemed to be turned off by mistake.

Good network security is that you also have HTTPS between the server and the proxy server. This can be done with a reverse proxy in a few ways. One way is the copy the cert from the server to the proxy. Another is SSL Passthrough. This lets a clients TLS requests pass through the proxy so the server can answer them with its valid certificate.

The redirect is there to ensure the server never sends sensitive authentication data over HTTP. This redirect only happens during the authentication of a user when they try loading a screen. This is a must.

This software is being designed for the new DIYer and someone that isn't into changing server side software. That's why there is easy install options and TLS cert setup built in.

Feel free to fork the code and modify it to allow this option. The redirect is in the "auth" function of server.js.
